# tetris-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-deployment
spec:
  replicas: 1 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      imagePullSecrets:
      - name: myregistrykey
      containers:
        - name: tetris
          image: nginx:latest
          ports:
            - containerPort: 80 # Replace with the port your Tetris game listens on
